<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px" />

# Python Fundamentals — Comprehensive Lab

### Topics covered
1. Variables and basic operations
2. Data types and type casting
3. Strings, indexing, slicing, and string methods
4. Arithmetic and comparison operators
5. Lists
6. Sets
7. Dictionaries
8. Tuples and data-structure casting
9. F-strings
10. `if / elif / else`
11. `for` loops
12. `while` loops
13. Functions



## Section I: Variables, Data Types, and Basic Operations


1) Create a variable `course_name` containing the text `'Python Bootcamp'`, then display its value.


In [3]:
course_name = "Python Bootcamp"
print(course_name)


Python Bootcamp


2) Store the number of learners in `learners`, the lesson duration in hours in `duration`, and whether the class is online in `is_online`. Use appropriate data types.


In [4]:
learners = 25
duration = 3
is_online = False

print(learners, duration, is_online)


25 3 False


3) Print the data type of `learners`, `duration`, and `is_online`.


In [5]:
print(type(learners))
print(type(duration))
print(type(is_online))


<class 'int'>
<class 'int'>
<class 'bool'>


4) A café sold 18 coffees in the morning and 27 in the afternoon. Store both values in variables and calculate the total coffees sold.


In [6]:
morning_coffees = 18
afternoon_coffees = 27

total_coffees = morning_coffees + afternoon_coffees
print(total_coffees)


45


5) A quantity arrives as the string `'48'`. Convert it to an integer and calculate what the quantity would be after adding 12.


In [7]:
quantity = "48"
quantity = int(quantity)

result = quantity + 12
print(result)


60


6) Store `year = 2026`. Convert it to text and create the sentence `'Data Science Bootcamp: 2026'` using concatenation.


In [87]:
year = 2026
year_text = str(year)

message = "Data Science Bootcamp: " + year_text
print(message)


Data Science Bootcamp: 2026


7) A measurement is stored as `14.87`. Convert it to an integer and print both the original and converted values.


In [9]:
measurement = 14.87
converted = int(measurement)

print(measurement)
print(converted)


14.87
14


8) Print `bool('')`, `bool('Python')`, `bool(0)`, and `bool(-1)`.


In [88]:
print(bool(""))
print(bool("Python"))
print(bool(0))
print(bool(-1))

# Empty strings and 0 are False.
# Non-empty strings and non-zero numbers are True.


False
True
False
True


9) Create variables for a city and country, then combine them into a single string in the format `City, Country`.


In [11]:
city = "Manama"
country = "Bahrain"

location = city + ", " + country
print(location)


Manama, Bahrain


10) Store the string `'Go! '` in a variable and use the multiplication operator to produce it five times.


In [12]:
word = "Go! "
print(word * 5)


Go! Go! Go! Go! Go! 


11) The expression `'12' * 2` works but `'12' + 2` does not. Test the first expression, then write a corrected version of the second.


In [13]:
print("12" * 2)

# "12" + 2 gives an error because Python cannot add a string and integer.
print(int("12") + 2)


1212
14


# Section II: Strings


12) Create a variable called `name` that is equal to your name.


In [14]:
name = "Ali"
print(name)


Ali


13) By adding strings together, introduce yourself in a string. For example `"Hello, my name is Tim!"`. You may use f-strings if you know what they are and prefer to use them.


In [15]:
print(f"Hello, my name is {name}!")


Hello, my name is Ali!


14) Define the string `fact` to be `"Python programming is fun."`


In [16]:
fact = "Python programming is fun."
print(fact)


Python programming is fun.


15) Index `fact` in order to get the `"o"` in `"Python"`.


In [17]:
print(fact[4])


o


16) Index `fact` in order to get the `"u"` in `"fun"` using a negative index.


In [18]:
print(fact[-3])


u


17) Slice `fact` in order to get the word `"programming"`.


In [19]:
print(fact[7:18])


programming


18) Uppercase `fact`.


In [20]:
print(fact.upper())


PYTHON PROGRAMMING IS FUN.


19) Replace the '.' at the end of `fact` with '!' point.


In [89]:
print(fact.replace(".", "!"))


Python programming is fun!


20) Use `.split()` to get the second word `programming`. 


In [90]:
print(fact.split()[1])

# Yes. split() makes it easy to work with individual words.


programming


21) Reverse `fact`.


In [91]:
print(fact[::-1])


.nuf si gnimmargorp nohtyP


22) Does `fact` contain the letter `y`? To find this answer, use the `in` keyword.


In [92]:
print("y" in fact)


True


23) How many `o`s does `fact` have?


In [93]:
print(fact.count("o"))


2


24) Replace all the `o`s in `fact` with an underscore (do not redefine `fact`).


In [94]:
print(fact.replace("o", "_"))


Pyth_n pr_gramming is fun.


25) Create `headline = '   learning PYTHON every day   '`. Remove the outer spaces and convert the result to title case.


In [95]:
headline = "   learning PYTHON every day   "

result = headline.strip().title()
print(result)


Learning Python Every Day


26) Using the existing `fact` string, find the starting position of the word `'fun'`.


In [96]:
print(fact.find("fun"))


22


27) Using the existing `fact` string, check whether it ends with a period.


In [97]:
print(fact.endswith("."))


True


28) From the string `'ABCDEFGHIJ'`, use slicing to return every second character starting from `A`.


In [98]:
text = "ABCDEFGHIJ"
print(text[::2])


ACEGI


29) Create `website = 'www.python.org'` and use string methods or slicing to extract only `'python'`.


In [99]:
website = "www.python.org"

result = website.replace("www.", "").replace(".org", "")
print(result)


python


30) Store your favorite programming language in a string and print its first three characters and its final three characters.


In [100]:
language = "Python"

print(language[:3])
print(language[-3:])


Pyt
hon


# Section III: Lists


31) Create a list `friends` of your three best friends, `"Alice"`, `"Bob"`, and `"Charlie"`.


In [101]:
friends = ["Alice", "Bob", "Charlie"]
print(friends)


['Alice', 'Bob', 'Charlie']


32) Find the length of `friends`.


In [102]:
print(len(friends))


3


33) Add your new friend `"Debbie"` to your list of `friends`.


In [103]:
friends.append("Debbie")
print(friends)


['Alice', 'Bob', 'Charlie', 'Debbie']


34) Charlie has no-showed to your piano recital. Remove him from your `friends`.


In [104]:
friends.remove("Charlie")
print(friends)


['Alice', 'Bob', 'Debbie']


35) Using the `.join()` method, join `friends` to look like this exactly: `"Alice & Bob & Debbie"`.


In [105]:
print(" & ".join(friends))


Alice & Bob & Debbie


36) What is the length of `[]`? What about `[[]]`? Why?


In [106]:
print(len([]))
print(len([[]]))

# [] contains no items.
# [[]] contains one item: an empty list.


0
1


For the next few problems, use this list:


In [107]:
nested_deep = [1, [2, 3], 4, [5, [6, 7, [8]]]]


37) What is the length of `nested_deep`?


In [1]:
nested_deep = [1, [2, 3], 4, [5, [6, 7, [8]]]]
print(len(nested_deep))


4


38) Index `nested_deep` to get the `5`.


In [109]:
print(nested_deep[3][0])


5


39) Index `nested_deep` to get the `8`.

*Hint: If your answer looks like `[8]`, that's not the correct answer!*


In [110]:
print(nested_deep[3][1][2][0])


8


40) Create `temperatures = [31, 34, 29, 36]` and add `33` to the end of the list.


In [111]:
temperatures = [31, 34, 29, 36]
temperatures.append(33)

print(temperatures)


[31, 34, 29, 36, 33]


41) Insert the value `30` as the second item in `temperatures`.


In [112]:
temperatures.insert(1, 30)
print(temperatures)


[31, 30, 34, 29, 36, 33]


42) Create `ratings = [4, 5, 3, 5, 2, 5]` and count how many times the rating `5` appears.


In [113]:
ratings = [4, 5, 3, 5, 2, 5]
print(ratings.count(5))


3


43) Create `expenses = [24, 11, 53, 18, 37]` and sort them from lowest to highest.


In [114]:
expenses = [24, 11, 53, 18, 37]
expenses.sort()

print(expenses)


[11, 18, 24, 37, 53]


44) Using the sorted `expenses` list, reverse it so the highest expense appears first.


In [115]:
expenses.reverse()
print(expenses)


[53, 37, 24, 18, 11]


45) Create `queue = ['A', 'B', 'C', 'D']`. Remove the last item with `.pop()` and save the removed value in `served_last`.


In [116]:
queue = ["A", "B", "C", "D"]

served_last = queue.pop()
print(served_last)
print(queue)


D
['A', 'B', 'C']


46) Create `cities = ['Manama', 'Dubai', 'Doha']` and make an independent copy called `backup_cities`.


In [117]:
cities = ["Manama", "Dubai", "Doha"]
backup_cities = cities.copy()

print(backup_cities)


['Manama', 'Dubai', 'Doha']


# Section IV: Sets


47) A survey produced `[101, 102, 101, 103, 104, 102, 105]`. Convert it to a set to obtain the unique participant IDs.


In [118]:
survey = [101, 102, 101, 103, 104, 102, 105]
unique_ids = set(survey)

print(unique_ids)


{101, 102, 103, 104, 105}


48) Create `morning = {'Ali', 'Noor', 'Maya'}` and `evening = {'Maya', 'Omar', 'Ali'}`.


In [119]:
morning = {"Ali", "Noor", "Maya"}
evening = {"Maya", "Omar", "Ali"}

print(morning)
print(evening)


{'Noor', 'Ali', 'Maya'}
{'Omar', 'Ali', 'Maya'}


49) Find everyone who attended either the morning or evening session.


In [120]:
print(morning.union(evening))


{'Maya', 'Noor', 'Ali', 'Omar'}


50) Find the people who attended both sessions.


In [121]:
print(morning.intersection(evening))


{'Ali', 'Maya'}


51) Find the people who attended the morning session but not the evening session.


In [122]:
print(morning.difference(evening))


{'Noor'}


52) Add `'Sara'` to the `morning` set.


In [123]:
morning.add("Sara")
print(morning)


{'Noor', 'Sara', 'Ali', 'Maya'}


53) Try to discard `'Hassan'` from the `morning` set using `.discard()`. Print the set afterward.


In [124]:
morning.discard("Hassan")
print(morning)

# No error occurs if the value is not found.


{'Noor', 'Sara', 'Ali', 'Maya'}


54) Check whether `{'Ali', 'Maya'}` is a subset of `morning`.


In [125]:
print({"Ali", "Maya"}.issubset(morning))


True


# Section V: Dictionaries


Use this dictionary for the next questions:
```python
student = {
    "name": "Ali",
    "age": 22,
    "score": 85
}
```


In [126]:
student = {"name": "Ali", "age": 22, "score": 85}


55) Create a dictionary called `product` with keys `name`, `price`, and `stock`, using values `Laptop` `450` `8`. Print only the product name.


In [127]:
product = {
    "name": "Laptop",
    "price": 450,
    "stock": 8
}

print(product["name"])


Laptop


56) Display all keys from the `product` dictionary.


In [128]:
print(product.keys())


dict_keys(['name', 'price', 'stock'])


57) Display all values from the `product` dictionary.


In [129]:
print(product.values())


dict_values(['Laptop', 450, 8])


58) Add a new key `category` to `product`.


In [130]:
product["category"] = "Electronics"
print(product)


{'name': 'Laptop', 'price': 450, 'stock': 8, 'category': 'Electronics'}


59) Increase the value stored in `stock` by 5.


In [131]:
product["stock"] += 5
print(product["stock"])


13


60) Use `.get()` to retrieve `price` from `product`.


In [ ]:
print(product.get("price"))

450


61) Loop through or display `product.items()` so each key-value pair can be seen.


In [133]:
for key, value in product.items():
    print(key, value)


name Laptop
price 450
stock 13
category Electronics


62) Remove the `category` entry using `.pop()` and store the removed category in a variable.


In [134]:
removed_category = product.pop("category")
print(removed_category)
print(product)


Electronics
{'name': 'Laptop', 'price': 450, 'stock': 13}


63) Add a key `monthly_sales` with the list `[12, 18, 15]`, then append a fourth month's sales value.


In [135]:
product["monthly_sales"] = [12, 18, 15]
product["monthly_sales"].append(20)

print(product)


{'name': 'Laptop', 'price': 450, 'stock': 13, 'monthly_sales': [12, 18, 15, 20]}


# Section VI: Tuples and Data-Structure Casting


64) Create `coordinates = (26.2, 50.6, 26.2, 49.9)`.


In [136]:
coordinates = (26.2, 50.6, 26.2, 49.9)
print(coordinates)


(26.2, 50.6, 26.2, 49.9)


65) Count how many times `26.2` appears in `coordinates`.


In [137]:
print(coordinates.count(26.2))


2


66) Find the index position of `49.9` in `coordinates`.


In [138]:
print(coordinates.index(49.9))


3


67) Attempt to replace the first value in `coordinates`. Add a comment explaining the result.


In [139]:
# coordinates[0] = 25.0
# This would raise a TypeError because tuples are immutable.


68) Convert `coordinates` into a list and store the result in `coordinate_list`.


In [140]:
coordinate_list = list(coordinates)
print(coordinate_list)


[26.2, 50.6, 26.2, 49.9]


69) Convert `['red', 'blue', 'red', 'green', 'blue']` into a set and print the result.


In [141]:
colors = ["red", "blue", "red", "green", "blue"]
unique_colors = set(colors)

print(unique_colors)


{'blue', 'green', 'red'}


70) Convert the word `'data'` into a list of individual characters.


In [142]:
letters = list("data")
print(letters)


['d', 'a', 't', 'a']


71) Convert `[('BHR', 'Bahrain'), ('UAE', 'United Arab Emirates')]` into a dictionary.


In [143]:
countries = dict([
    ("BHR", "Bahrain"),
    ("UAE", "United Arab Emirates")
])

print(countries)


{'BHR': 'Bahrain', 'UAE': 'United Arab Emirates'}


# Section VII: Operators and F-Strings


72) A box contains 29 items packed into groups of 6. Use operators to calculate the number of complete groups, the remainder, and `6` raised to the power of `2`.


In [144]:
items = 29
group_size = 6

complete_groups = items // group_size
remainder = items % group_size
power_result = 6 ** 2

print(complete_groups)
print(remainder)
print(power_result)


4
5
36


73) Create `sales = 250` and `target = 200`. Write comparisons that check whether sales met the target, exceeded it, and are different from the target.


In [145]:
sales = 250
target = 200

print(sales >= target)
print(sales > target)
print(sales != target)


True
True
True


74) Create variables `employee = 'Mariam'` and `department = 'Analytics'`. Use an f-string to print a sentence introducing the employee and department.


In [146]:
employee = "Mariam"
department = "Analytics"

print(f"{employee} works in the {department} department.")


Mariam works in the Analytics department.


75) Store a product name, quantity, and unit price. Use an f-string to display all three values in one sentence.


In [147]:
product_name = "Mouse"
quantity = 3
unit_price = 12.5

print(f"Product: {product_name}, Quantity: {quantity}, Unit price: {unit_price}")


Product: Mouse, Quantity: 3, Unit price: 12.5


76) Given `distance = 12`, use an expression directly inside an f-string to print how far 3 trips would cover.


In [148]:
distance = 12
print(f"3 trips cover {distance * 3} km.")


3 trips cover 36 km.


# Section VIII: Conditional Statements


77) Ask the user for the current temperature. Print `Cold` below 15, `Mild` from 15 to 24, `Warm` from 25 to 34, and `Hot` for 35 or above.


In [150]:
temperature = float(input("Enter the temperature: "))

if temperature < 15:
    print("Cold")
elif temperature <= 24:
    print("Mild")
elif temperature <= 34:
    print("Warm")
else:
    print("Hot")


Hot


78) Ask the user for an order amount. Apply these messages: below 10 → `Small order`, 10 to below 50 → `Regular order`, 50 to below 100 → `Large order`, and 100 or more → `Bulk order`.


In [ ]:
amount = float(input("Enter the order amount: "))

if amount < 10:
    print("Small order")
elif amount < 50:
    print("Regular order")
elif amount < 100:
    print("Large order")
else:
    print("Bulk order")


Small order


79) Ask the user for the number of late arrivals this month. Print `Perfect attendance` for 0, `Good` for 1, `Warning` for 2 or 3, and `Review required` for more than 3.


In [ ]:
late_arrivals = int(input("Enter number of late arrivals: "))

if late_arrivals == 0:
    print("Perfect attendance")
elif late_arrivals == 1:
    print("Good")
elif late_arrivals <= 3:
    print("Warning")
else:
    print("Review required")


Warning


80) Ask the user for an account balance. Print whether the balance is positive, negative, or exactly zero.


In [ ]:
balance = float(input("Enter account balance: "))

if balance > 0:
    print("Positive")
elif balance < 0:
    print("Negative")
else:
    print("Zero")


Positive


81) Ask the user for a whole number of seats. Print whether the number of seats is even or odd.


In [ ]:
seats = int(input("Enter number of seats: "))

if seats % 2 == 0:
    print("Even")
else:
    print("Odd")


Even


82) Ask the user for `age` and whether they have a ticket (`yes` or `no`). Allow entry only when age is at least 18 and a ticket is present.


In [1]:
age = int(input("Enter your age: "))
ticket = input("Do you have a ticket? yes/no: ").lower()

if age >= 18 and ticket == "yes":
    print("Entry allowed")
else:
    print("Entry denied")


Entry denied


# Section IX: For Loops


83) Use `range()` to print the numbers from 5 through 15.


In [151]:
for number in range(5, 16):
    print(number)


5
6
7
8
9
10
11
12
13
14
15


84) Loop through `departments = ['Sales', 'Finance', 'Operations']` and print `Department: <name>` for each item.


In [153]:
departments = ["Sales", "Finance", "Operations"]

for department in departments:
    print(f"Department: {department}")


Department: Sales
Department: Finance
Department: Operations


85) Given `daily_sales = [120, 95, 140, 110, 135]`, calculate the total using a `for` loop without using `sum()`.


In [154]:
daily_sales = [120, 95, 140, 110, 135]
total = 0

for sale in daily_sales:
    total += sale

print(total)


600


86) Given `delivery_times = [22, 41, 18, 35, 50, 27]`, build a new list containing only delivery times of 30 minutes or less.


In [155]:
delivery_times = [22, 41, 18, 35, 50, 27]
fast_deliveries = []

for time in delivery_times:
    if time <= 30:
        fast_deliveries.append(time)

print(fast_deliveries)


[22, 18, 27]


87) Using `prices = [8, 15, 23, 6, 19]`, calculate the total of only the prices that are at least 15.


In [156]:
prices = [8, 15, 23, 6, 19]
total = 0

for price in prices:
    if price >= 15:
        total += price

print(total)


57


88) Given `inventory = {'Laptop': 4, 'Mouse': 0, 'Monitor': 7, 'Keyboard': 0}`, loop through it and print whether each product is `In stock` or `Out of stock`.


In [157]:
inventory = {
    "Laptop": 4,
    "Mouse": 0,
    "Monitor": 7,
    "Keyboard": 0
}

for product, stock in inventory.items():
    if stock > 0:
        print(product, "In stock")
    else:
        print(product, "Out of stock")


Laptop In stock
Mouse Out of stock
Monitor In stock
Keyboard Out of stock


89) Given `weekly_sales = {'Ali': [10, 12, 9], 'Sara': [7, 8, 11], 'Ahmed': [15, 14, 16]}`, print only the people whose sales were at least 10 on every recorded day.


In [158]:
weekly_sales = {
    "Ali": [10, 12, 9],
    "Sara": [7, 8, 11],
    "Ahmed": [15, 14, 16]
}

for person, sales in weekly_sales.items():
    passed_all = True

    for value in sales:
        if value < 10:
            passed_all = False

    if passed_all:
        print(person)


Ahmed


90) Loop through `[13, 20, 7, 18, 25]` and print whether each number is even or odd.


In [159]:
numbers = [13, 20, 7, 18, 25]

for number in numbers:
    if number % 2 == 0:
        print(number, "Even")
    else:
        print(number, "Odd")


13 Odd
20 Even
7 Odd
18 Even
25 Odd


91) Use nested loops with `teams = [['Ali', 'Sara'], ['Maya', 'Omar']]` to print every team member one at a time.


In [160]:
teams = [["Ali", "Sara"], ["Maya", "Omar"]]

for team in teams:
    for member in team:
        print(member)


Ali
Sara
Maya
Omar


92) Count how many values in `[72, 55, 91, 44, 68, 83]` are at least 70.


In [161]:
values = [72, 55, 91, 44, 68, 83]
count = 0

for value in values:
    if value >= 70:
        count += 1

print(count)


3


93) Create a list containing the cube of every integer from 1 through 8 using a `for` loop.


In [162]:
cubes = []

for number in range(1, 9):
    cubes.append(number ** 3)

print(cubes)


[1, 8, 27, 64, 125, 216, 343, 512]


# Section X: While Loops


94) Set `battery = 5`. Use a `while` loop to print the battery level and decrease it by 1 until it reaches 0.


In [163]:
battery = 5

while battery >= 0:
    print(battery)
    battery -= 1


5
4
3
2
1
0


95) Use `while True` to repeatedly increase `points` by 2. Stop the loop when `points` reaches or exceeds 10.


In [164]:
points = 0

while True:
    points += 2
    print(points)

    if points >= 10:
        break


2
4
6
8
10


96) Given `tasks = ['email', 'report', 'meeting', 'backup', 'logout']`, use a `while` loop to process items in order and stop when `'backup'` is reached.


In [165]:
tasks = ["email", "report", "meeting", "backup", "logout"]
index = 0

while index < len(tasks):
    task = tasks[index]
    print(task)

    if task == "backup":
        break

    index += 1


email
report
meeting
backup


97) Keep asking the user to enter a positive number. Stop only when a value greater than 0 is entered, then print `Accepted`.


In [166]:
while True:
    number = float(input("Enter a positive number: "))

    if number > 0:
        print("Accepted")
        break


Accepted


98) Start with `savings = 0`. Add 25 during each loop iteration until savings reaches at least 200. Print the final savings amount.


In [167]:
savings = 0

while savings < 200:
    savings += 25

print(savings)


200


99) Create a countdown from 10 to 2, decreasing by 2 each time, then print `Finished!`.


In [2]:
count = 10

while count >= 2:
    print(count)
    count -= 2

print("Finished!")


10
8
6
4
2
Finished!


# Section XI: Functions


100) Create a function `welcome_student(student_name)` that returns a welcome message containing the student's name.


In [ ]:
def welcome_student(student_name):
    return f"Welcome, {student_name}!"

print(welcome_student("Ali"))


101) Ask the user for a city name, pass it into a function called `city_message(city)`, and print the returned sentence.


In [ ]:
def city_message(city):
    return f"You entered the city: {city}"

city = input("Enter a city: ")
print(city_message(city))


102) Create a function `calculate_average(values)` that calculates and returns the average of a list without using `sum()`.


In [ ]:
def calculate_average(values):
    total = 0

    for value in values:
        total += value

    return total / len(values)


103) Test `calculate_average()` using `[12, 18, 24, 30]`.


In [ ]:
print(calculate_average([12, 18, 24, 30]))


104) Create a function `add_tax(prices)` that returns a new list where each price is increased by 10%.


In [ ]:
def add_tax(prices):
    taxed_prices = []

    for price in prices:
        taxed_prices.append(price * 1.10)

    return taxed_prices

print(add_tax([10, 20, 30]))


105) Create a function `rectangle_stats(length, width)` that returns both the rectangle's area and perimeter.


In [ ]:
def rectangle_stats(length, width):
    area = length * width
    perimeter = 2 * (length + width)

    return area, perimeter

print(rectangle_stats(5, 3))


106) Create a function `is_positive(number)` that returns `True` only when the number is greater than zero.


In [ ]:
def is_positive(number):
    return number > 0

print(is_positive(10))
print(is_positive(-3))


107) Create a function `shipping_fee(amount)` that returns `0` when the order is at least 50, otherwise returns `5`.


In [ ]:
def shipping_fee(amount):
    if amount >= 50:
        return 0
    else:
        return 5

print(shipping_fee(65))
print(shipping_fee(30))


108) Create a function `smallest_value(numbers)` that returns the smallest number in a list without using `min()`.


In [ ]:
def smallest_value(numbers):
    smallest = numbers[0]

    for number in numbers:
        if number < smallest:
            smallest = number

    return smallest

print(smallest_value([8, 3, 11, 2, 7]))


109) Create a function `count_available(stock_levels)` that returns how many values in the list are greater than 0.


In [ ]:
def count_available(stock_levels):
    count = 0

    for stock in stock_levels:
        if stock > 0:
            count += 1

    return count

print(count_available([5, 0, 3, 0, 8]))


110) Create a function `count_vowels(text)` that counts and returns the number of vowels in a string without using `.count()`.


In [3]:
def count_vowels(text):
    count = 0
    vowels = "aeiouAEIOU"

    for character in text:
        if character in vowels:
            count += 1

    return count

print(count_vowels("Python is useful"))


5


111) **Simple Access System**

Create a dictionary mapping three employee IDs to department names. Ask the user for an employee ID. If it exists, print the employee's department; otherwise print `Unknown employee`.


In [4]:
employees = {
    "E001": "Sales",
    "E002": "Finance",
    "E003": "IT"
}

employee_id = input("Enter employee ID: ")

if employee_id in employees:
    print(employees[employee_id])
else:
    print("Unknown employee")


Sales
